# Generated by Django 4.2.3 on 2023-08-01 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_seller_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('display_image', models.ImageField(upload_to='product_img')),
                ('display_image1', models.ImageField(upload_to='product_img')),
                ('display_image3', models.ImageField(upload_to='product_img')),
                ('regular_price', models.PositiveIntegerField()),
                ('sale_price', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('Clothing', 'clothing'), ('Shoes', 'Shoes'), ('Accessories', 'Accessories')], max_length=100)),
                ('product_type', models.CharField(choices=[('Formal Shirt', 'Formal Shirt'), ('Formal Pant', 'Formal Pant'), ('Casual Shirt', 'Casual Shirt'), ('Casual Pant', 'Casual Pant'), ('T-Shirt', 'T-Shirt'), ('Analog watch', 'Analog watch'), ('Smart watch', 'Smart watch'), ('Sport Shoes', 'Sport Shoes'), ('Casual Shoes', 'Casual Shoes')], max_length=100)),
                ('collection', models.CharField(choices=[('Regular', 'Regular'), ('Summer', 'Summer'), ('Winter', 'Winter'), ('Traditional', 'Traditional'), ('Party', 'Party')], max_length=100)),
                ('tags', models.CharField(choices=[('Clothes', 'Clothes'), ('Skin', 'Skin'), ('Body', 'Body')], max_length=100)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.seller')),
            ],
        ),
    ]
