# Generated by Django 4.2.3 on 2023-08-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.CharField(choices=[('FITNESS', 'FITNESS'), ('LIFESTYLE', 'LIFESTYLE'), ('DISCIPLINE', 'EXERCISE'), ('EXERCISE', 'EXERCISE'), ('HEALTH', 'HEALTH'), ('Skin', 'Skin'), ('Body', 'Body')], max_length=100),
        ),
    ]
