# Generated by Django 4.2.3 on 2023-08-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_product_date_time_alter_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Formal Shirt', 'Formal Shirt'), ('Formal Pant', 'Formal Pant'), ('Casual Shirt', 'Casual Shirt'), ('Casual Pant', 'Casual Pant'), ('T-Shirt', 'T-Shirt'), ('Analog watch', 'Analog watch'), ('Smart watch', 'Smart watch'), ('Sport Shoes', 'Sport Shoes'), ('Casual Shoes', 'Casual Shoes'), ('Sunglasses', 'Sunglasses')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.CharField(choices=[('FITNESS', 'FITNESS'), ('LIFESTYLE', 'LIFESTYLE'), ('DISCIPLINE', 'DISCIPLINE'), ('EXERCISE', 'EXERCISE'), ('HEALTH', 'HEALTH'), ('Skin', 'Skin'), ('Body', 'Body')], max_length=100),
        ),
    ]
