# Generated by Django 4.2.3 on 2023-08-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_product_product_type_alter_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='role',
        ),
        migrations.AddField(
            model_name='seller',
            name='Organization_role',
            field=models.CharField(default='Seller', max_length=100),
        ),
        migrations.AddField(
            model_name='seller',
            name='company_logo',
            field=models.ImageField(default='', upload_to='company_logo/'),
        ),
        migrations.AddField(
            model_name='seller',
            name='company_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='seller',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='seller',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='seller',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='seller',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='seller',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
