# Generated by Django 4.2.3 on 2023-08-05 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_role_user_organization_role_user_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='display_image3',
            new_name='display_image2',
        ),
    ]
