# Generated by Django 4.2.3 on 2023-08-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='date_time',
            field=models.CharField(default='', max_length=100),
        ),
    ]
